// This file provides types for the API.
//
// Code generated by MarkRosemaker/openapi-codegen. DO NOT EDIT.

package toggl

import (
	"encoding/json/v2"
	"net/url"
	"time"
	"uuid"

	"github.com/MarkRosemaker/jsonutil"
	"github.com/go-api-libs/types"
)

var jsonOpts = json.JoinOptions(
	json.RejectUnknownMembers(true),
	json.WithMarshalers(json.JoinMarshalers(
		json.MarshalToFunc(jsonutil.URLMarshal),
		json.MarshalToFunc(jsonutil.DurationMarshalIntSeconds),
	)),
	json.WithUnmarshalers(json.JoinUnmarshalers(
		json.UnmarshalFromFunc(jsonutil.URLUnmarshal),
		json.UnmarshalFromFunc(jsonutil.DurationUnmarshalIntSeconds),
	)),
)

// GetMeParams holds the query parameters for GetMe.
type GetMeParams struct {
	// Retrieve user related data (clients, projects, tasks, tags, workspaces, time entries, etc.)
	WithRelatedData bool
}

// ListTimeEntriesParams holds the query parameters for ListTimeEntries.
type ListTimeEntriesParams struct {
	// Get entries modified since this date using UNIX timestamp, including deleted ones.
	Since int
	// Get entries with start time before the given date.
	Before time.Time
	// Get entries with start time from the given time. To be used with end_date.
	StartDate time.Time
	// Get entries with start time until the given time. To be used with start_date.
	EndDate time.Time
	// Should the response contain meta data such as `client_name`, `project_name`, `project_color`, `project_active`, `project_billable`, `user_name`, and `user_avatar_url`.
	Meta bool
	// Include sharing details in the response
	IncludeSharing bool
}

// APIErrorString defines a model
type APIErrorString string

// Clients defines a model
type Clients []WorkClient

// EventMetadata defines a model
type EventMetadata struct{}

// NewOrganization defines a model
type NewOrganization struct {
	// Name of the organization
	Name string `json:"name,omitzero"`
	// Name of the workspace
	WorkspaceName string `json:"workspace_name,omitzero"`
}

// NewTimeEntry defines a model
type NewTimeEntry struct {
	// Whether the time entry is marked as billable, optional, default false
	Billable bool `json:"billable"`
	// Must be provided when creating a time entry and should identify the service/application used to create it
	CreatedWith string `json:"created_with,omitzero"`
	// Time entry description, optional
	Description string `json:"description,omitzero"`
	// Time entry duration. For running entries should be negative, preferable -1
	Duration time.Duration `json:"duration"`
	// Deprecated: Used to create a time entry with a duration but without a stop time. This parameter can be ignored.
	Duronly       bool           `json:"duronly,omitempty"`
	EventMetadata *EventMetadata `json:"event_metadata,omitempty"`
	// Project ID, legacy field
	Pid *int `json:"pid,omitempty"`
	// Project ID, optional
	ProjectID *int `json:"project_id,omitempty"`
	// List of user IDs to share this time entry with
	SharedWithUserIds []int `json:"shared_with_user_ids,omitzero"`
	// Start time, required for creation.
	Start time.Time `json:"start,omitzero"`
	// If provided during creation, the date part will take precedence over the date part of "start". Format: 2006-11-07
	StartDate string `json:"start_date,omitzero"`
	// Stop time in UTC, can be omitted if it's still running or created with "duration".
	// If "stop" and "duration" are provided, values must be consistent (start + duration == stop)
	Stop string `json:"stop,omitzero"`
	// Used when updating an existing time entry
	TagAction TagAction `json:"tag_action,omitzero"`
	// IDs of tags to add/remove
	TagIds []int `json:"tag_ids,omitzero"`
	// Names of tags to add/remove. If name does not exist as tag, one will be created automatically
	Tags []string `json:"tags"`
	// Task ID, optional
	TaskID *int `json:"task_id,omitempty"`
	// Task ID, legacy field
	Tid *int `json:"tid,omitempty"`
	// Time Entry creator ID, legacy field
	UID *int `json:"uid,omitempty"`
	// Time Entry creator ID, if omitted will use the requester user ID
	UserID *int `json:"user_id,omitempty"`
	// Workspace ID, legacy field
	Wid *int `json:"wid,omitempty"`
	// Workspace ID
	WorkspaceID int `json:"workspace_id"`
}

// Options defines a model
type Options map[string]string

// Organization defines a model
type Organization struct {
	// Organization ID
	ID int `json:"id"`
	// Organization Name
	Name string `json:"name,omitzero"`
	// Organization plan ID
	PricingPlanID int `json:"pricing_plan_id"`
	// Organization's creation date
	CreatedAt time.Time `json:"created_at,omitzero"`
	// Organization's last modification date
	At              time.Time `json:"at,omitzero"`
	ServerDeletedAt struct{}  `json:"server_deleted_at"`
	// Is true when the organization option is_multi_workspace_enabled is set
	IsMultiWorkspaceEnabled bool `json:"is_multi_workspace_enabled"`
	// Whether the organization is currently suspended
	SuspendedAt struct{} `json:"suspended_at"`
	// Number of organization users
	UserCount int       `json:"user_count"`
	TrialInfo TrialInfo `json:"trial_info"`
	IsUnified bool      `json:"is_unified"`
	// Maximum number of workspaces allowed for the organization
	MaxWorkspaces int    `json:"max_workspaces"`
	Permissions   string `json:"permissions,omitzero"`
	// Whether the requester is an admin of the organization
	Admin bool `json:"admin"`
	// Whether the requester is a the owner of the organization
	Owner bool `json:"owner"`
	// The subscription plan name the org is currently on. Free or any plan name coming from payment provider
	PricingPlanName string `json:"pricing_plan_name,omitzero"`
	// The subscription plan is an enterprise plan
	PricingPlanEnterprise bool `json:"pricing_plan_enterprise"`
	// How far back free workspaces in this org can access data.
	MaxDataRetentionDays *int `json:"max_data_retention_days,omitempty"`
}

// Organizations defines a model
type Organizations []Organization

// Project defines a model
type Project struct {
	// Project ID
	ID          int `json:"id"`
	WorkspaceID int `json:"workspace_id"`
	// Client ID
	ClientID  int    `json:"client_id"`
	Name      string `json:"name,omitzero"`
	IsPrivate bool   `json:"is_private"`
	// Whether the project is active or archived
	Active bool `json:"active"`
	// Last updated date
	At time.Time `json:"at,omitzero"`
	// Creation date
	CreatedAt       time.Time `json:"created_at,omitzero"`
	ServerDeletedAt struct{}  `json:"server_deleted_at"`
	// Color
	Color string `json:"color,omitzero"`
	// Whether the project is billable, premium feature
	Billable bool     `json:"billable"`
	Template struct{} `json:"template"`
	// Whether estimates are based on task hours, premium feature
	AutoEstimates bool `json:"auto_estimates"`
	// RecurringPeriod
	CurrentPeriod *EventMetadata `json:"current_period,omitempty"`
	// End date
	EndDate string `json:"end_date,omitzero"`
	// Estimated hours
	EstimatedHours int `json:"estimated_hours"`
	// Estimated seconds
	EstimatedSeconds int      `json:"estimated_seconds"`
	Rate             struct{} `json:"rate"`
	RateLastUpdated  struct{} `json:"rate_last_updated"`
	// Currency, premium feature
	Currency            string   `json:"currency,omitzero"`
	Recurring           bool     `json:"recurring"`
	TemplateID          struct{} `json:"template_id"`
	RecurringParameters struct{} `json:"recurring_parameters"`
	// Fixed fee, premium feature
	FixedFee float64 `json:"fixed_fee"`
	// Actual hours
	ActualHours int `json:"actual_hours"`
	// Actual seconds
	ActualSeconds int      `json:"actual_seconds"`
	TasksCount    struct{} `json:"tasks_count"`
	CanTrackTime  bool     `json:"can_track_time"`
	StartDate     string   `json:"start_date,omitzero"`
	Status        string   `json:"status,omitzero"`
	Wid           int      `json:"wid"`
	// Client ID legacy field
	Cid      int  `json:"cid"`
	IsShared bool `json:"is_shared"`
	Pinned   bool `json:"pinned"`
	// The external ID of the linked entity in the external system (e.g. JIRA/SalesForce)
	IntegrationExtID string `json:"integration_ext_id,omitzero"`
	// The external type of the linked entity in the external system (e.g. JIRA/SalesForce)
	IntegrationExtType string `json:"integration_ext_type,omitzero"`
	// The provider (e.g. JIRA/SalesForce) that has an entity linked to this Toggl Track entity
	IntegrationProvider string `json:"integration_provider,omitzero"`
}

// Projects defines a model
type Projects []Project

// SimpleOrganization defines a model
type SimpleOrganization struct {
	ID            int    `json:"id"`
	Name          string `json:"name,omitzero"`
	Permissions   string `json:"permissions,omitzero"`
	WorkspaceID   int    `json:"workspace_id"`
	WorkspaceName string `json:"workspace_name,omitzero"`
}

// Tag defines a model
type Tag struct {
	ID          int       `json:"id"`
	WorkspaceID int       `json:"workspace_id"`
	Name        string    `json:"name,omitzero"`
	At          time.Time `json:"at,omitzero"`
	CreatorID   int       `json:"creator_id"`
}

// Used when updating an existing time entry
type TagAction string

const (
	TagActionAdd    TagAction = "add"
	TagActionDelete TagAction = "delete"
)

// Valid indicates whether the value is a known member of the TagAction enum.
func (e TagAction) Valid() bool {
	switch e {
	case TagActionAdd, TagActionDelete:
		return true
	default:
		return false
	}
}

// Tags defines a model
type Tags []Tag

// TimeEntries defines a model
type TimeEntries []TimeEntry

// TimeEntry defines a model
type TimeEntry struct {
	ID              int           `json:"id"`
	WorkspaceID     int           `json:"workspace_id"`
	ProjectID       int           `json:"project_id"`
	TaskID          struct{}      `json:"task_id"`
	Billable        bool          `json:"billable"`
	Start           time.Time     `json:"start,omitzero"`
	Stop            time.Time     `json:"stop,omitzero"`
	Duration        time.Duration `json:"duration"`
	Description     string        `json:"description,omitzero"`
	Tags            []string      `json:"tags"`
	TagIds          []string      `json:"tag_ids"`
	Duronly         bool          `json:"duronly"`
	At              time.Time     `json:"at,omitzero"`
	ServerDeletedAt time.Time     `json:"server_deleted_at,omitzero"`
	UserID          int           `json:"user_id"`
	UID             int           `json:"uid"`
	Wid             int           `json:"wid"`
	Pid             int           `json:"pid"`
	ClientName      string        `json:"client_name,omitzero"`
	ProjectName     string        `json:"project_name,omitzero"`
	ProjectColor    string        `json:"project_color,omitzero"`
	ProjectActive   bool          `json:"project_active,omitempty"`
	ProjectBillable bool          `json:"project_billable,omitempty"`
	UserName        string        `json:"user_name,omitzero"`
	UserAvatarURL   *url.URL      `json:"user_avatar_url,omitempty"`
}

// TrialInfo defines a model
type TrialInfo struct {
	// Whether the organization's subscription is currently on trial
	Trial bool `json:"trial"`
	// When a trial is available for this organization
	TrialAvailable bool `json:"trial_available"`
	// When the trial ends
	TrialEndDate string `json:"trial_end_date,omitzero"`
	// When the trial payment is due
	NextPaymentDate string `json:"next_payment_date,omitzero"`
	// What was the previous plan before the trial
	LastPricingPlanID int `json:"last_pricing_plan_id"`
	// True, if neither the organization nor the owner has never had a trial before
	CanHaveTrial bool     `json:"can_have_trial"`
	TrialPlanID  struct{} `json:"trial_plan_id"`
}

// UserWithRelated defines a model
type UserWithRelated struct {
	ID                 int         `json:"id"`
	APIToken           string      `json:"api_token,omitzero"`
	Email              types.Email `json:"email,omitzero"`
	Fullname           string      `json:"fullname,omitzero"`
	Timezone           string      `json:"timezone,omitzero"`
	TogglAccountsID    string      `json:"toggl_accounts_id,omitzero"`
	DefaultWorkspaceID int         `json:"default_workspace_id"`
	BeginningOfWeek    int         `json:"beginning_of_week"`
	ImageURL           url.URL     `json:"image_url,omitzero"`
	CreatedAt          time.Time   `json:"created_at,omitzero"`
	UpdatedAt          time.Time   `json:"updated_at,omitzero"`
	OpenidEmail        struct{}    `json:"openid_email"`
	OpenidEnabled      bool        `json:"openid_enabled"`
	CountryID          int         `json:"country_id"`
	HasPassword        bool        `json:"has_password"`
	At                 time.Time   `json:"at,omitzero"`
	IntercomHash       string      `json:"intercom_hash,omitzero"`
	OauthProviders     []string    `json:"oauth_providers"`
	// A timestamp when the authorization user session object was last updated.
	AuthorizationUpdatedAt time.Time `json:"authorization_updated_at,omitzero"`
	Tags                   Tags      `json:"tags,omitzero"`
	// Clients, null if with_related_data was not set to true or if the user does not have any clients
	Clients     Clients     `json:"clients,omitzero"`
	TimeEntries TimeEntries `json:"time_entries,omitzero"`
	Options     *Options    `json:"options,omitempty"`
	// Projects, null if with_related_data was not set to true or if the user does not have any projects
	Projects      Projects   `json:"projects,omitzero"`
	Workspaces    Workspaces `json:"workspaces,omitzero"`
	TwoFaEnabled  bool       `json:"2fa_enabled,omitempty"`
	UserAccountID *int       `json:"user_account_id,omitempty"`
}

// WorkClient defines a model
type WorkClient struct {
	// Client ID
	ID int `json:"id"`
	// Workspace ID
	Wid int `json:"wid"`
	// true, if the client is archived
	Archived bool `json:"archived"`
	// Name of the client
	Name string `json:"name,omitzero"`
	// When was the last update
	At time.Time `json:"at,omitzero"`
	// The ID of the user who created the client
	CreatorID int `json:"creator_id"`
	// The external ID of the linked entity in the external system (e.g. JIRA/SalesForce)
	IntegrationExtID string `json:"integration_ext_id,omitzero"`
	// The external type of the linked entity in the external system (e.g. JIRA/SalesForce)
	IntegrationExtType string `json:"integration_ext_type,omitzero"`
	// The provider (e.g. JIRA/SalesForce) that has an entity linked to this Toggl Track entity
	IntegrationProvider string `json:"integration_provider,omitzero"`
	Notes               string `json:"notes,omitzero"`
	// List of authorization permissions for this client.
	Permissions string `json:"permissions,omitzero"`
}

// Workspace defines a model
type Workspace struct {
	ID                          int       `json:"id"`
	OrganizationID              int       `json:"organization_id"`
	Name                        string    `json:"name,omitzero"`
	Premium                     bool      `json:"premium"`
	BusinessWs                  bool      `json:"business_ws"`
	Admin                       bool      `json:"admin"`
	Role                        string    `json:"role,omitzero"`
	SuspendedAt                 string    `json:"suspended_at,omitzero"`
	ServerDeletedAt             struct{}  `json:"server_deleted_at"`
	DefaultHourlyRate           struct{}  `json:"default_hourly_rate"`
	RateLastUpdated             struct{}  `json:"rate_last_updated"`
	DefaultCurrency             string    `json:"default_currency,omitzero"`
	OnlyAdminsMayCreateProjects bool      `json:"only_admins_may_create_projects"`
	OnlyAdminsMayCreateTags     bool      `json:"only_admins_may_create_tags"`
	OnlyAdminsSeeBillableRates  bool      `json:"only_admins_see_billable_rates"`
	OnlyAdminsSeeTeamDashboard  bool      `json:"only_admins_see_team_dashboard"`
	ProjectsBillableByDefault   bool      `json:"projects_billable_by_default"`
	ProjectsPrivateByDefault    bool      `json:"projects_private_by_default"`
	ProjectsEnforceBillable     bool      `json:"projects_enforce_billable"`
	LimitPublicProjectData      bool      `json:"limit_public_project_data"`
	LastModified                time.Time `json:"last_modified,omitzero"`
	ReportsCollapse             bool      `json:"reports_collapse"`
	Rounding                    int       `json:"rounding"`
	RoundingMinutes             int       `json:"rounding_minutes"`
	APIToken                    uuid.UUID `json:"api_token,omitzero"`
	At                          time.Time `json:"at,omitzero"`
	LogoURL                     url.URL   `json:"logo_url,omitzero"`
	IcalURL                     string    `json:"ical_url,omitzero"`
	IcalEnabled                 bool      `json:"ical_enabled"`
	CsvUpload                   struct{}  `json:"csv_upload"`
	Subscription                struct{}  `json:"subscription"`
	HideStartEndTimes           bool      `json:"hide_start_end_times"`
	WorkingHoursInMinutes       struct{}  `json:"working_hours_in_minutes"`
}

// Workspaces defines a model
type Workspaces []Workspace
