// This file provides types for the API.
//
// Code generated by github.com/MarkRosemaker DO NOT EDIT.

package toggl

import (
	"net/url"
	"time"

	"github.com/go-api-libs/types"
)

// User defines a model
type User struct {
	ID                     int             `json:"id"`
	APIToken               string          `json:"api_token"`
	Email                  types.Email     `json:"email"`
	Fullname               string          `json:"fullname"`
	Timezone               string          `json:"timezone"`
	TogglAccountsID        string          `json:"toggl_accounts_id"`
	DefaultWorkspaceID     int             `json:"default_workspace_id"`
	BeginningOfWeek        int             `json:"beginning_of_week"`
	ImageURL               url.URL         `json:"image_url"`
	CreatedAt              time.Time       `json:"created_at"`
	UpdatedAt              time.Time       `json:"updated_at"`
	OpenidEmail            UserOpenidEmail `json:"openid_email"`
	OpenidEnabled          bool            `json:"openid_enabled"`
	CountryID              UserCountryID   `json:"country_id"`
	HasPassword            bool            `json:"has_password"`
	At                     time.Time       `json:"at"`
	IntercomHash           string          `json:"intercom_hash"`
	OauthProviders         []string        `json:"oauth_providers"`
	AuthorizationUpdatedAt time.Time       `json:"authorization_updated_at"`
}

// UserOpenidEmail defines a model
type UserOpenidEmail struct{}

// UserCountryID defines a model
type UserCountryID struct{}
